### ISSUE TITLE
[Bug] can't download files

### ISSUE THREAD

**Issue by tenzap** [duckduckgo/Android#1721]
### Describe the bug

Files are not downloadable

### How to Reproduce

Go to https://f-droid.org/
Download the f droid app from that website.
It will seem Android States to download it since there is such a notification. But in fact nothing happens and eventually the file can't be found anywhere and the notification disappeared.

### Expected behavior

File should be downloaded and named correctly.

Everything works fine on fennec or Firefox.

I've been having that issue for a few months

### Environment

```markdown
- DDG App Version: 5.109.0 ml

Device: Xiaomi Redmi note 9s
Android 11
```

**Comment by tenzap** [comment]
It looks like duckduckgo forwards the download to the download manager of the phone which in my case is:

com.android.providers.downloads.ui
Version 21.05.14.10

The app looks like a built in app provided by Xiaomi but the app Id doesn't mention Xiaomi.

**Comment by tenzap** [comment]
Problem actually seems vpn related. If vpn is disabled in Android settings, the download manager starts downloading.

**Comment by cmonfortep** [comment]
Thanks @tenzap. We are aware of some issues around downloads (some of them when the VPN in enabled). We are currently working on a project that will improve downloads 👍

**Comment by 2011** [comment]
Adding a comment to this so I see updates. :)

I encountered a problem trying to download a file today (I do have a VPN enabled). While I didn't try a lot of different files, the ones from this folder on google drive kept giving download failed messages:

https://drive.google.com/drive/folders/1BfeK39boriHy-9q76eXLLqbCwfV17-Gv

On the other hand (doing a minimal amount of troubleshooting), downloading a file from github worked perfectly.

Also on 5.109.0 (multiple devices, multiple android versions).

**Comment by tenzap** [comment]
With release 5.113.1 it is still problematic

**Comment by indurs** [comment]
I'm currently using DuckDuckGo as my default browser. 

Using version 5.113.1

Device - Pixel 2
Android version - 11

I can download from https://f-droid.org/

![Screenshot_20220226-121627](https://user-images.githubusercontent.com/12825812/155833980-b26969e8-4423-4dda-87d9-fb143444eb3f.png)

![Screenshot_20220226-121655](https://user-images.githubusercontent.com/12825812/155834046-4bc343ba-5007-497b-b8a3-cfead02bce3d.png)


![Screenshot_20220226-121617](https://user-images.githubusercontent.com/12825812/155833924-912585dd-3169-44e1-afc7-9d406bbf6534.png)

**Comment by malmstein** [comment]
This has been fixed as per https://github.com/duckduckgo/Android/releases/tag/5.113.1

**Comment by tenzap** [comment]
As I said, with release 5.113.1 I'm still unable to download: as soon as I am on a VPN, download doesn't start. This is the case with 5.113.1 and was also the case at the time I submitted the bug report.

BTW, I mentionned fdroid just as an example, the issue is not related to APK or fdroid, it happens with any file type (PDF...)

Shall I open a new issue?


Device: Xiaomi Redmi note 9s
Android 11
