### ISSUE TITLE
[Bug] Cannot download PDFs from GitHub

### ISSUE THREAD

**Issue by bluecmd** [duckduckgo/Android#3645]
### Describe the bug

Hello,

I'm unable to download PDF files from GitHub when using the DDG app specifically.

### How to Reproduce

* Navigate to any PDF hosted on GitHub. E.g. https://github.com/mozilla/pdf.js/blob/master/test/pdfs/ArabicCIDTrueType.pdf
 * Press the "..." next to the branch name.
 * Press "Download"
 * Observe that nothing happens

If you do the same steps in Firefox on Android the PDF is downloaded.

### Expected behavior

The PDF file is downloaded

### Environment

```markdown
- DDG App Version: 5.174.0
- Device: Pixel 6 Pro
- OS: Android 13
```

**Comment by Rajkdea123** [comment]
Can i resolve this issue?

**Comment by bluecmd** [comment]
> Can i resolve this issue?

I still can't download the linked PDF in the latest DDG Browser, so I would say no. Are you able to download it using the reproduce instructions?

**Comment by Rajkdea123** [comment]
Ok, I'll try,I didn't do it yet

**Comment by woheller69** [comment]
In my view this is due to GitHub's content security policy. They do not want us to inject code to retrieve the pdf in the blob.
Doesn't work with my FREE Bowser either.

**Comment by anikiki** [comment]
This is solved in `5.209.2`.

**Comment by woheller69** [comment]
> This is solved in `5.209.2`.

No, it is not solved.
Still nothing happens when clicking "Download"

**Comment by anikiki** [comment]
@woheller69 Due to WebView constraints, this works only if your installed System WebView version is above "126.0.6478.40". Right now, the latest one is " 128.0.6613.127".
