### ISSUE TITLE
The app opens another tab of same page

### ISSUE THREAD

**Issue by FaqatZubair1** [duckduckgo/Android#4937]
### Describe the bug

Whenever I go back from the browser and reopen it, if it has a page already opened, it'll re-open the same page on another tab while keeping tge previous tab also open. Another issue is that, whenever I press the fire button, the app becomes unresponsive for sometime and doesn't open any new tabs. You can see both the issues in the attached video file (I forgot to show the previously opened tab, but trust me that's also there).

### How to Reproduce

https://github.com/user-attachments/assets/4361a429-ec3a-4cf6-a66c-de0a6e72b338

### Expected behavior

The tab I already have opened should remain opened without even refreshing until prompted so.

### Environment

```markdown
- DDG App Version:5.211.0
- Device: motorola 
- OS: Android 14
```

**Comment by karlenDimla** [comment]
Hello! Thank you for you bug report. I am able to reproduce the specific issue on my end. 

I've added it to our backlog so we can find time to prioritise, investigate and hopefully address it at some point.

**Comment by lakshay6907** [comment]
@karlenDimla 
Do you know if this issue is still open?

**Comment by FaqatZubair1** [comment]
@lakshay6907 
Yes, it is still open. I don't know what is the team doing, they're taking so long to fix simple bugs.

**Comment by lakshay6907** [comment]
> @lakshay6907 Yes, it is still open. I don't know what is the team doing, they're taking so long to fix simple bugs.

I'd like to contribute to this issue. May I try to work on finding a fix for it?

**Comment by MahdiRahmani80** [comment]
Hi, I've tried replicating this bug, but I can't! 
I may wonder what I am doing wrong or if this bug is already fixed, because this issue has been going on for five months.
I found a new bug that might related to this but is not exactly like this issue:

1. search 
2. open a page
3. get out of DDG 
4. reopen DDG (you see that page)
5. press back
6. press back

You should see a blank page with the step 2 page URL, if you press back, get out from DDG, if click the search bar and search you can open that page.

**Comment by FaqatZubair1** [comment]
@MahdiRahmani80 no sir, the bug is still there it is still happening to me, I guess they are struggling to find it.
